services:
  - type: web
    name: vse-web
    env: node
    plan: starter
    region: frankfurt
    branch: main
    rootDir: .
    buildCommand: npm install
    startCommand: npm run start
    autoDeploy: true
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: CHAT_API_URL
        sync: false
      - key: CHAT_API_TOKEN
        sync: false
      - key: DATA_DIR
        value: /var/data
