services:
  - type: web
    name: vse-web
    env: node
    plan: free
    region: frankfurt
    branch: main
    rootDir: .
    buildCommand: npm install
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: CHAT_API_URL
        sync: false
      - key: CHAT_API_TOKEN
        sync: false
